### ISSUE TITLE
 Issue 1 to 5

### ISSUE THREAD

**Issue by zz19990220** [zz19990220/T510_2025#3]
# Client Milestone 1 - GitHub Issues

---

## ✅ Issue 1: Download buttons export empty files

**Title:**  
Download buttons export empty files

**Body:**
```
The download buttons currently produce 0-byte files.

**Steps to Reproduce**
1. Run `app.py` and generate any story.
2. Click **Download Audio** or **Download Video**.
3. The downloaded file size is 0 B.

**Expected**
Buttons should export playable `.mp3` and `.mp4` files.

**Suspected Cause**
`st.download_button` currently receives an empty `io.BytesIO()`.

**Suggested Fix**
Write the actual audio/video buffer to `BytesIO()` and verify non-zero file output.
```

---

## ✅ Issue 2: Invalid package in requirements.txt

**Title:**  
requirements.txt contains invalid package `matplot`

**Body:**
```
Running `pip install -r requirements.txt` fails because **matplot** is not a valid PyPI package.

Please replace it with:

```
matplotlib>=3.8
```
```

---

## ✅ Issue 3: Add common folders to `.gitignore`

**Title:**  
Add common folders to `.gitignore`

**Body:**
```
Current `.gitignore` only ignores `__pycache__`.

Please add:

```
# Virtual environments
.venv/
env/
# Editors
.idea/
.vscode/
# Byte-code cache
*.py[cod]
__pycache__/
```
```

---

## ✅ Issue 4: Replace mocked `generate_music_snippet()` with real API

**Title:**  
Replace mocked `generate_music_snippet()` with real API

**Body:**
```
The `generate_music_snippet()` function currently returns placeholder rhythm and mood data.

Please integrate a real music generation API or model such as:
- Suno / StableAudio
- EnCodec + LLM prompting
- Any suitable open-source LoRA-based option

Update the README and tests accordingly.
```

---

## ✅ Issue 5: Add CI with pytest and increase test coverage

**Title:**  
Add CI with pytest and increase test coverage

**Body:**
```
To ensure quality and reproducibility, please set up GitHub Actions for CI.

**Add tests for:**
- `detect_emotion()` – correct keys and range
- all animation functions – return valid PIL.Image.Image, correct size

**Sample CI workflow:**
```yaml
name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pytest
```
```
